---
- name: Update homebrew
  homebrew: update_homebrew=yes

- name: Install homebrew packages
  homebrew:
    name={{ item.name }}
    state={{ item.state | default('present') }}
    install_options={{ item.install_options | default('') }}
  with_items: homebrew_packages

- name: Install homebrew-cask packages
  homebrew_cask: name={{ item }}
  with_items: homebrew_cask_packages
